### ISSUE TITLE
Erros

### ISSUE THREAD

**Issue by brunolcarlos** [caglardurmus/react-native-insta-story#1]
I Tried to use but there is erros showing on the console.

**Comment by caglardurmus** [comment]
Can you send me your code sample? Also error.

**Comment by brunolcarlos** [comment]
Hi, I appreciate your response, first error the npm install  did not installed the src folder, I did manually but did't works because the system was telling about Invariant Violation: Tried to register two views with the same name RNCSafeAreaProvider.
Thank you so much

**Comment by caglardurmus** [comment]
Hi, install v1.0.3 and pod install

**Comment by brunolcarlos** [comment]
![Simulator Screen Shot - iPhone 12 - 2021-09-16 at 12 22 43](https://user-images.githubusercontent.com/12675160/133649495-bb72eb51-edaf-4ef9-bd7a-bfc520fb8a24.png)
HI, i'm getting this error now

**Comment by caglardurmus** [comment]
Hi again, remove old version and install last v1.0.5 then nix pod-install and build again.
