### ISSUE TITLE
Cant swipe to watch previous stories 

### ISSUE THREAD

**Issue by luckychdhr** [caglardurmus/react-native-insta-story#10]
if i clicked on second story , i can only see second and third and soon ... stories not the first one using swipe left.

**Comment by caglardurmus** [comment]
It's normal for it to work this way. Instagram uses it in the same way, we tried to emulate it. You cannot go back to before the story you clicked on, it is now your start story.

**Comment by luckychdhr** [comment]
> It's normal for it to work this way. Instagram uses it in the same way, we tried to emulate it. You cannot go back to before the story you clicked on, it is now your start story.

But in instagram you can go back to before story you clicked on it. Can you please try to add this in upcoming commit of yours, it will be very helpful. Thanks for the library and all the efforts you have put to make this good one.

**Comment by Niltonsf** [comment]
Have you found a way to implement this
