### ISSUE TITLE
> It's normal for it to work this way. Instagram uses it in the same way, we tried to emulate it. You cannot go back to before the story you clicked on, it is now your start story.

### ISSUE THREAD

**Issue by luckychdhr** [caglardurmus/react-native-insta-story#13]
> It's normal for it to work this way. Instagram uses it in the same way, we tried to emulate it. You cannot go back to before the story you clicked on, it is now your start story.

But in instagram you can go back to before story you clicked on it. Can you please try to add this in upcoming commit of yours, it will be very helpful. Thanks for the library and all the efforts you have put to make this good one.

_Originally posted by @luckychdhr in https://github.com/caglardurmus/react-native-insta-story/issues/10#issuecomment-1018187614_

**Comment by caglardurmus** [comment]
I'll work on this update if I can find the time.

**Comment by Niltonsf** [comment]
This would be something great to fix!
