### ISSUE TITLE
Android error, Working fine iOS

### ISSUE THREAD

**Issue by jensonjohn001** [caglardurmus/react-native-insta-story#16]
* What went wrong:
A problem occurred evaluating project ':react-native-insta-story'.
> Plugin with id 'maven' not found

"react-native": "0.67.2",
"react-native-insta-story": "^1.1.7",

**Comment by MertHaddad** [comment]
Tested on "react-native" : 0.68.1 and it worked without problems. (Android Version ) 
try to delete the node_modules & package-lock.json then run` npm i` then `expo r -c`

**Comment by harshal311989** [comment]
I face same issue in  "react-native": "0.68.2", 
![Screenshot 2022-06-28 at 5 54 21 PM](https://user-images.githubusercontent.com/75067288/176177835-8f0387c0-d6ec-4038-b9b1-e1cee9e91b1f.png)

Any solution on this?

**Comment by SatuNarola** [comment]
I face same issue in "react-native": "0.68.2" Anyone have Solution Please Share Here.....

>

**Comment by caglardurmus** [comment]
you can use new version(1.1.8)
