### ISSUE TITLE
error: package com.reactlibrary does not exist import com.reactlibrary.InstaStoryPackage;

### ISSUE THREAD

**Issue by khunghang16** [caglardurmus/react-native-insta-story#18]
I update version react native to 0.67. I have a issue when run android.

error: package com.reactlibrary does not exist import com.reactlibrary.InstaStoryPackage;

Info:
"react": "17.0.2",
"react-native": "0.67.4"
<img width="793" alt="Screen Shot 2022-04-17 at 1 46 14 AM" src="https://user-images.githubusercontent.com/27754944/163687620-15da8951-da3c-4eb2-92ee-ada85f7b2543.png">
,

**Comment by caglardurmus** [comment]
check the new version
