### ISSUE TITLE
Doesn't work with dynamic data

### ISSUE THREAD

**Issue by icodervj** [caglardurmus/react-native-insta-story#22]
I tried changing data source to api data response but it doesn't work.
Anyone else faced the same problem?

**Comment by onneti2013** [comment]
> I tried changing data source to api data response but it doesn't work. Anyone else faced the same problem?

I had the same problem and it can be solved with a setstate of already loaded data

const [storiesloaded, setStoriesloaded] = useState(0);

        { storiesloaded != 0 &&
            <InstaStory data={stories}
            duration={10}
            onStart={item => console.log(item)}
            onClose={item => console.log('close: ', item)}
            customSwipeUpComponent={<View>
                                <Text>Swipe</Text>
                            </View>}
            style={{marginTop: 30}}/>
        }
Just after your dynamic data is loaded you change storiesloaded to 1

**Comment by altiparmakzeynep** [comment]
@icodervj I have same issue. Did you solve?

**Comment by altiparmakzeynep** [comment]
@onneti2013 It's working! Thank you.
