### ISSUE TITLE
dynamic data not working

### ISSUE THREAD

**Issue by Standin-Alone** [caglardurmus/react-native-insta-story#25]

**Comment by onneti2013** [comment]
> _No description provided._

I had the same problem and it can be solved with a setstate of already loaded data

    const [storiesloaded, setStoriesloaded] = useState(0);

            { storiesloaded != 0 &&
                <InstaStory data={stories}
                duration={10}
                onStart={item => console.log(item)}
                onClose={item => console.log('close: ', item)}
                customSwipeUpComponent={<View>
                                    <Text>Swipe</Text>
                                </View>}
                style={{marginTop: 30}}/>
            }

Just after your dynamic data is loaded you change storiesloaded to 1
