### ISSUE TITLE
A way to determine if the data has already been seen

### ISSUE THREAD

**Issue by Niltonsf** [caglardurmus/react-native-insta-story#28]
I believe that a way that we could determine if the data has been seen. I believe most of people will be using this with apis

**Comment by hilmia** [comment]
It would be great to have an event per story. 

Let's say that someone has 2 stories, and the user only saw the first one.
On next click on the avatar, it should start from the second (unseen) story.

**Comment by huyhai** [comment]
let ob = {
                user_id: 1,
                user_image: url,
                user_name: name,
                stories: stories,
                seen: true,
              };
add seen param

**Comment by Anas-Mushtaq** [comment]
Is there any way to check the single story of a person is seen or not if he have uploaded multiple stories

**Comment by IB3N** [comment]
/@Niltonsf - would #43 work?
