### ISSUE TITLE
Loading gets slower when increasing the number of stories 

### ISSUE THREAD

**Issue by Thilina-B** [caglardurmus/react-native-insta-story#3]
The loading part of the Cube-navigation is getting slower when we have lots of stories. what is the best way to solve  this issue?

**Comment by isuvorov** [comment]
+1

**Comment by caglardurmus** [comment]
Hello, when I have the opportunity, I will test with larger data. If you have a better suggestion for this effect, you can share it.

**Comment by luckychdhr** [comment]
The loading part of the Cube-navigation is getting slower because all the stories running in background when viewing any story, so can you please set the animation to run on one story at a time.
