### ISSUE TITLE
#video support

### ISSUE THREAD

**Issue by piratechetan** [caglardurmus/react-native-insta-story#40]
thanks for a package that is easy to use and customizable please also add video support in the stories view.

**Comment by dprajapati1179** [comment]
When video support will be added ?

**Comment by lucasdzuc** [comment]
@aglardurmus

**Comment by lucasdzuc** [comment]
@metehankurucu

**Comment by jainminals** [comment]
You can customise node modules

**Comment by bilal1031** [comment]
@lucasdzuc @piratechetan @dprajapati1179, I created an npm package that you can use to have the video support. If you want to use that, it is tweaked for expo-managed projects but it should work for react-native-cli too.
Here's the link
https://www.npmjs.com/package/expo-insta-story

**Comment by Clever-Shivanshu** [comment]
@bilal1031 , It is so slow
![Screenshot_2024-01-16-17-35-06-80_f73b71075b1de7323614b647fe394240](https://github.com/caglardurmus/react-native-insta-story/assets/92704295/3762c680-2bda-4f19-819d-513c87f07cae)
